version: "3.7"

services:
  sales-predictor:
    image: sales-predictor:latest
    ports:
      - 5000:5000
    build: .
    depends_on: 
        - predictor-db

  predictor-db:
    image: mongo:3.7
    container_name: predictor-db
    ports:
      - 27017:27017
