version: "3.7"

services:
  sales-estimator-backend:
    image: sales-estimator-backend:latest
    container_name: sales-estimator-backend
    ports:
      - 5000:5000
    depends_on: 
        - sales-estimator-db
    environment: 
      - MONGO_URI=mongodb://sales-estimator-db/estimations
    build: .
  
  sales-estimator-portainer:
    image: portainer/portainer:latest
    container_name: sales-estimator-portainer
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro

  sales-estimator-db:
    image: mongo:4.0
    container_name: sales-estimator-db
    ports:
      - 27017
